import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const ORIGIN="https://pisite2543nac-netizen.github.io";
const cors={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"};
function secret(){try{const raw=Deno.env.get('SUPABASE_SECRET_KEYS');if(raw)return JSON.parse(raw).default}catch{}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const clean=(v:unknown)=>String(v||'').trim().replace(/[^A-Za-z0-9._-]/g,'').slice(0,64);
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
  const svc=createClient(Deno.env.get('SUPABASE_URL')!,secret(),{auth:{persistSession:false,autoRefreshToken:false}}),token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');
  const {data:u,error:ue}=await svc.auth.getUser(token);if(ue||!u.user)return json({error:'Unauthorized'},401);
  const {data:ap}=await svc.from('profiles').select('role,active,approval_status').eq('id',u.user.id).single();if(!ap||ap.role!=='admin'||!ap.active||ap.approval_status!=='approved')return json({error:'Forbidden'},403);
  const b=await req.json(),studentCode=String(b.student_code||'').trim(),username=clean(b.username||studentCode),password=String(b.password||''),fullName=String(b.full_name||'').trim();
  if(username.length<4||password.length<8||!fullName)return json({error:'INVALID_USER_DATA'},400);if(username.toLowerCase()==='pisit2000')return json({error:'USERNAME_RESERVED'},409);if(studentCode&&!/^\d{1,15}$/.test(studentCode))return json({error:'INVALID_STUDENT_CODE'},400);
  const dup=await svc.from('profiles').select('id').or(`username.ilike.${username}${studentCode?`,student_code.eq.${studentCode}`:''}`).limit(1);if(dup.error)return json({error:dup.error.message},500);if((dup.data||[]).length)return json({error:'USERNAME_EXISTS'},409);
  const contact=String(b.email||'').trim().toLowerCase()||null;if(contact&&!/^\S+@\S+\.\S+$/.test(contact))return json({error:'INVALID_CONTACT_EMAIL'},400);
  let roomName=b.class_name?String(b.class_name):null;const classroomId=b.classroom_id?String(b.classroom_id):null;if(classroomId){const rr=await svc.from('classrooms').select('id,name,active').eq('id',classroomId).single();if(rr.error||!rr.data?.active)return json({error:'CLASSROOM_NOT_FOUND'},400);roomName=rr.data.name}
  const gradeLevel=String(b.grade_level||'').trim()||null,roomLabel=String(b.room_label||'').trim()||null,department=String(b.department||'').trim()||null,major=String(b.major||'').trim()||null;if(!roomName&&gradeLevel&&roomLabel)roomName=`${gradeLevel}${roomLabel}`;
  const authEmail=`${username.toLowerCase()}@docfullnr.local`,role=b.role==='admin'?'admin':'user';const {data:created,error}=await svc.auth.admin.createUser({email:authEmail,password,email_confirm:true,user_metadata:{full_name:fullName,username,student_code:studentCode||null}});if(error)return json({error:error.message},400);
  const id=created.user.id,now=new Date().toISOString();const {error:pe}=await svc.from('profiles').update({full_name:fullName,display_name:fullName,username,role,class_name:roomName,student_code:studentCode||null,grade_level:gradeLevel,room_label:roomLabel,department,major,seat_number:b.seat_number?Number(b.seat_number):null,contact_email:contact,active:true,approval_status:'approved',approval_requested_at:now,approved_at:now,approved_by:u.user.id,academic_status:'studying'}).eq('id',id);if(pe){await svc.auth.admin.deleteUser(id);return json({error:pe.message},500)}
  if(classroomId){const me=await svc.from('classroom_memberships').upsert({classroom_id:classroomId,user_id:id,seat_number:b.seat_number?Number(b.seat_number):null,active:true},{onConflict:'classroom_id,user_id'});if(me.error){await svc.auth.admin.deleteUser(id);return json({error:me.error.message},500)}}
  await svc.from('audit_logs').insert({actor_id:u.user.id,action:'CREATE_USER',entity_type:'profile',entity_id:id,metadata:{username,role,classroom_id:classroomId,student_code:studentCode||null,approval_status:'approved'}});return json({ok:true,id,username,approval_status:'approved'});
}catch(e){return json({error:e instanceof Error?e.message:'Server error'},500)}});
